version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"  # RabbitMQ Management UI
      - "8081:5672"    # RabbitMQ Messaging Port
    networks:
      - rabbitmq_network

  python-app:
    build: ./src
    depends_on:
      - rabbitmq
    volumes:
      - ./src:/app
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge
